import dotenv from 'dotenv';
dotenv.config();

const TIMEZONE = process.env.TIMEZONE || 'Asia/Kolkata';

/**
 * Formats a Date object to a local date string (YYYY-MM-DD) in the configured timezone.
 * @param {Date} date
 * @returns {string} YYYY-MM-DD
 */
export function getLocalDateStr(date = new Date()) {
  const formatter = new Intl.DateTimeFormat('en-US', {
    timeZone: TIMEZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });
  const parts = formatter.formatToParts(date);
  const year = parts.find(p => p.type === 'year').value;
  const month = parts.find(p => p.type === 'month').value;
  const day = parts.find(p => p.type === 'day').value;
  return `${year}-${month}-${day}`;
}

/**
 * Formats a Date object to today's local date string (convenience wrapper).
 * @returns {string} YYYY-MM-DD
 */
export function getTodayStr() {
  return getLocalDateStr(new Date());
}

/**
 * Gets a local date string with an offset of days in the configured timezone.
 * @param {number} daysOffset
 * @param {Date|string} baseDate
 * @returns {string} YYYY-MM-DD
 */
export function getOffsetLocalDateStr(daysOffset, baseDate = new Date()) {
  let d;
  if (typeof baseDate === 'string') {
    d = parseLocalDateStr(baseDate);
  } else {
    d = new Date(baseDate.getTime());
  }

  // If the date is a timezone-independent UTC date (e.g. from parseLocalDateStr), offset in UTC
  if (d.getUTCHours() === 12 && d.getUTCMinutes() === 0) {
    d.setUTCDate(d.getUTCDate() + daysOffset);
    return formatUTCDateStr(d);
  }

  // Otherwise, calculate the local YYYY-MM-DD, parse it to a stable UTC midnight, apply offset, and format
  const localStr = getLocalDateStr(d);
  const parsed = parseLocalDateStr(localStr);
  parsed.setUTCDate(parsed.getUTCDate() + daysOffset);
  return formatUTCDateStr(parsed);
}

/**
 * Parses a local date string (YYYY-MM-DD) into a timezone-independent Date object (representing 12:00 PM UTC).
 * @param {string} dateStr
 * @returns {Date}
 */
export function parseLocalDateStr(dateStr) {
  const [year, month, day] = dateStr.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, day, 12, 0, 0));
}

/**
 * Formats a UTC Date object (specifically those generated by parseLocalDateStr) into a YYYY-MM-DD string.
 * @param {Date} date
 * @returns {string} YYYY-MM-DD
 */
export function formatUTCDateStr(date) {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}
